# 网站 url
baseURL = "https://www.dilyslyu.com"
# [en, zh-cn, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 主题，可配置 themesDir 默认在 ./themes
theme = "LoveIt"
# 网站标题
title = "Dilys.Lyu Blog - A Front Programmer."
# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true
# 忽略文件
ignoreFiles = [ "\\.gitignore$", "\\.git" ]
[params]
  # LoveIt 主题版本
  version = "0.2.X"
  # 网站默认主题 ("light", "dark", "auto")
  defaultTheme = "auto"
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/dilyslyu/dilyslyu"
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # 日期格式
  dateFormat = "2006年01月02日"
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/logo.svg"]
  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
    # 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = "/jonnyhub-logo.png"
      # 标题名称
      name = "Dilys's Blog"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ' '
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
  # 页面底部信息配置
  [params.footer]
    enable = true
    # 自定义内容 (支持 HTML 格式)
    custom = ''
    # 是否显示 Hugo 和主题信息
    hugo = false
    # 是否显示版权信息
    copyright = true
    # 是否显示作者
    author = true
    # 网站创立年份
    since = 2015
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = '<a href="http://beian.miit.gov.cn/"; target=_blank>浙ICP备18052140号</a>'
    # 许可协议信息 (支持 HTML 格式)
    license= ''
  # Section (所有文章) 页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 10
    # 日期格式 (月和日)
    dateFormat = "01月02日"
    # RSS 文章数目
    rss = 10

  # List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 10
    # 日期格式 (月和日)
    dateFormat = "01月日"
    # RSS 文章数目
    rss = 100

  # 文章页面配置
  [params.page]
    # 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = true
    # 是否使用 twemoji
    twemoji = true
    # 是否使用 lightgallery
    lightgallery = true
    # 是否使用 ruby 扩展语法
    ruby = true
    # 是否使用 fraction 扩展语法
    fraction = true
    # 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 是否显示原始 Markdown 文档内容的链接
    linkToMarkdown = true
    # 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # 是否使目录自动折叠展开
      auto = true
    # 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 20
    # KaTeX 数学公式配置 (KaTeX https://katex.org/)
    [params.page.math]
      enable = false
      # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # 默认行内定界符是 $ ... $ 和 \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
    # Mapbox GL JS 配置 (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      # 是否添加 NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
      navigation = true
      # 是否添加 GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
      geolocate = true
      # 是否添加 ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
      scale = true
      # 是否添加 FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
      fullscreen = true
    # 文章页面的分享信息设置
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = true
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false
    # 评论系统设置
    [params.page.comment]
      enable = true
      # Disqus 评论系统设置 (https://disqus.com/)
      [params.page.comment.disqus]
        enable = false
        # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
        shortname = ""
      # Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
      [params.page.comment.gitalk]
        enable = false
        owner = "hellenhub"
        repo = "comment-repo"
        clientId = "6f984a0eb0834583c1c3"
        clientSecret = "85600facf1191a819ed0b70e9f9bebfc93a984c1"
      # Valine 评论系统设置 (https://github.com/xCss/Valine)
      [params.page.comment.valine]
        enable = true
        appId = "FtykkqDTKcnmJIc4ulSmbigS-gzGzoHsz"
        appKey = "eslLDIyTAN1xfmmdbTDgu4to"
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = true
        serverURLs = "https://ftykkqdt.lc-cn-n1-shared.com"
      # Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      # Telegram comments 评论系统设置 (https://comments.app/)
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      # Commento comments 评论系统设置 (https://commento.io/)
      [params.page.comment.commento]
        enable = false
    # SEO 配置
    [params.page.seo]
      # 出版者信息
      [params.page.seo.publisher]
        name = "Dilys.Lyu"
        [params.page.seo.publisher.logo]
          url = "logo.png"
          width = 127
          height = 40
      # Logo 信息
      [params.page.seo.logo]
        url = "logo.png"
        width = 127
        height = 40
      # 图片信息
      [params.page.seo.image]
        url = "cover.png"
        width = 800
        height = 600

  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

# 网站分析配置
  [params.analytics]
    enable = false
    # Google 分析
    [params.analytics.google]
      id = ""
      # 是否匿名化用户 IP
      anonymizeIP = true
    # Fathom 分析
    [params.analytics.fathom]
      id = ""
      # 自行托管追踪器时的主机路径
      server = ""

  # CSS 和 JS 文件的 CDN 设置
  [params.cdn]
    # normalize.css@8.0.1 https://github.com/necolas/normalize.css
    normalizeCSS = 'https://cdn.bootcdn.net/ajax/libs/normalize/8.0.1/normalize.min.css'
    # fontawesome-free@5.13.0 https://fontawesome.com/
    fontawesomeFreeCSS = ''
    # simple-icons@2.9.0 https://github.com/simple-icons/simple-icons
    simpleIconsPrefix = ''
    animateCSS = 'https://cdn.bootcdn.net/ajax/libs/animate.css/4.1.0/animate.min.css'
    # smooth-scroll@16.1.3 https://github.com/cferdinandi/smooth-scroll
    smoothScrollJS = 'https://cdn.bootcdn.net/ajax/libs/smooth-scroll/16.1.3/smooth-scroll.min.js'
    # autocomplete.js@0.37.1 https://github.com/algolia/autocomplete.js
    autocompleteJS = 'https://cdn.bootcdn.net/ajax/libs/autocomplete.js/0.37.1/autocomplete.min.js'
    # lunr.js@2.3.8 https://lunrjs.com/
    lunrJS = 'https://cdn.bootcdn.net/ajax/libs/lunr.js/2.3.8/lunr.min.js'
    # algoliasearch@4.2.0 https://github.com/algolia/algoliasearch-client-javascript
    algoliasearchJS = ''
    # lazysizes@5.2.0 https://github.com/aFarkas/lazysizes
    lazysizesJS = '/lib/lazysizes/lazysizes.min.js'
    # twemoji@12.1.5 https://github.com/twitter/twemoji
    twemojiJS = 'https://cdn.bootcdn.net/ajax/libs/twemoji/12.0.4/twemoji.min.js'
    # lightgallery.js@1.1.3 lg-thumbnail@1.1.0 lg-zoom@1.1.0 https://github.com/sachinchoolur/lightgallery.js
    lightgalleryCSS = 'https://cdn.bootcdn.net/ajax/libs/lightgallery-js/1.2.0/css/lightgallery.min.css'
    lightgalleryJS = 'https://cdn.bootcdn.net/ajax/libs/lightgallery-js/1.2.0/js/lightgallery.min.js'
    lightgalleryThumbnailJS = ''
    lightgalleryZoomJS = ''
    # clipboard.js@2.0.6 https://github.com/zenorocha/clipboard.js
    clipboardJS = 'https://cdn.bootcdn.net/ajax/libs/clipboard.js/2.0.6/clipboard.min.js'
    # sharer.js@0.4.0 https://github.com/ellisonleao/sharer.js
    sharerJS = 'https://cdn.bootcdn.net/ajax/libs/sharer.js/0.4.0/sharer.min.js'
    # typeit@7.0.3 https://github.com/alexmacarthur/typeit
    typeitJS = 'https://cdn.bootcdn.net/ajax/libs/typeit/7.0.4/typeit.min.js'
    # katex@0.11.1 https://katex.org/
    katexCSS = 'https://cdn.bootcdn.net/ajax/libs/KaTeX/0.11.1/katex.min.css'
    katexJS = 'https://cdn.bootcdn.net/ajax/libs/KaTeX/0.11.1/katex.min.js'
    katexAutoRenderJS = 'https://cdn.bootcdn.net/ajax/libs/KaTeX/0.11.1/contrib/auto-render.min.js'
    katexCopyTexCSS = 'https://cdn.bootcdn.net/ajax/libs/KaTeX/0.11.1/contrib/copy-tex.min.css'
    katexCopyTexJS = 'https://cdn.bootcdn.net/ajax/libs/KaTeX/0.11.1/contrib/copy-tex.min.js'
    katexMhchemJS = 'https://cdn.bootcdn.net/ajax/libs/KaTeX/0.11.1/contrib/mhchem.min.js'
    # mermaid@8.5.0 https://github.com/knsv/mermaid
    mermaidJS = 'https://cdn.bootcdn.net/ajax/libs/mermaid/8.7.0/mermaid.min.js'
    # echarts@4.7.0 https://echarts.apache.org/
    echartsJS = 'https://cdn.bootcdn.net/ajax/libs/echarts/4.8.0/echarts.min.js'
    echartsMacaronsJS = ''
    # mapbox-gl@1.9.1 https://docs.mapbox.com/mapbox-gl-js
    mapboxGLCSS = 'https://cdn.bootcdn.net/ajax/libs/mapbox-gl/1.12.0/mapbox-gl.min.css'
    mapboxGLJS = 'https://cdn.bootcdn.net/ajax/libs/mapbox-gl/1.12.0/mapbox-gl.min.js'
    # aplayer@1.10.1 https://github.com/MoePlayer/APlayer
    aplayerCSS = 'https://cdn.bootcdn.net/ajax/libs/aplayer/1.10.1/APlayer.min.css'
    aplayerJS = 'https://cdn.bootcdn.net/ajax/libs/aplayer/1.10.1/APlayer.min.js'
    # meting@2.0.1 https://github.com/metowolf/MetingJS
    metingJS = ''
    # gitalk@1.6.2 https://github.com/gitalk/gitalk
    gitalkCSS = 'https://cdn.bootcdn.net/ajax/libs/gitalk/1.6.2/gitalk.min.css'
    gitalkJS = 'https://cdn.bootcdn.net/ajax/libs/gitalk/1.6.2/gitalk.min.js'
    # valine@1.4.9 https://valine.js.org/
    valineJS = 'https://cdn.bootcdn.net/ajax/libs/valine/1.4.14/Valine.min.js'

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# 作者配置
[author]
  name = "Dilys.Lyu"
  email = "jonny0624@gmail.com"
  link = "https://github.com/hellenhub"

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.8

# Permalinks 文章路径配置
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":year/:month/:filename"
# 隐私信息配置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  # Google Analytics 相关隐私 (被 params.analytics.google 替代)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = false
  [privacy.youtube]
    privacyEnhanced = true

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
# 中文配置，支持更多语言
[languages]
  [languages.zh-cn]
    weight = 1
    # # 网站语言, 仅在这里 CN 大写
    # languageCode = "zh-CN"
    # 语言名称
    languageName = "简体中文"
    # 是否包括中日韩文字
    hasCJKLanguage = true
    # 默认每页列表显示的文章数目
    paginate = 10
    # [UA-XXXXXXXX-X] 谷歌分析代号
    googleAnalytics = ""
    # 版权描述，仅仅用于 SEO
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    # 菜单配置
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        identifier = "posts"
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = ""
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
        post = ""
        name = "所有文章"
        url = "/posts/"
        title = "所有文章"
        weight = 1
      [[languages.zh-cn.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "标签"
        url = "/tags/"
        title = "文章标签"
        weight = 2
      [[languages.zh-cn.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "分类"
        url = "/categories/"
        title = "文章分类"
        weight = 3
      # [[languages.zh-cn.menu.main]]
      #   identifier = "blockchain"
      #   pre = ""
      #   post = ""
      #   name = "区块链专题"
      #   url = "/blockchain"
      #   title = "Blockchain 相关资料"
      #   weight = 4
      # [[languages.zh-cn.menu.main]]
      #   identifier = "golang"
      #   pre = ""
      #   post = ""
      #   name = "GoLang 专题"
      #   url = "/golang"
      #   title = "GoLang 相关资料"
      #   weight = 5
      # [[languages.zh-cn.menu.main]]
      #   identifier = "manual"
      #   name = "手册"
      #   url = "/categories/写作手册/"
      #   title = "写作手册"
      #   weight = 4
      # [[languages.zh-cn.menu.main]]
      #   identifier = "resume"
      #   pre = ""
      #   post = ""
      #   name = "简历"
      #   url = "/resume"
      #   title = "张向阳 | 个人简历 | Java 开发工程师"
      #   weight = 5
      [[languages.zh-cn.menu.main]]
        identifier = "about"
        pre = ""
        post = ""
        name = "关于"
        url = "/about"
        title = "关于 | About - Hellen's Blog"
        weight = 6
      [[languages.zh-cn.menu.main]]
        identifier = "bookmark"
        pre = ""
        post = ""
        name = "书签"
        url = "/bookmark"
        title = "书签 | 我的常用书签"
        weight = 7
      [[languages.zh-cn.menu.main]]
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw'></i>"
        name = ""
        url = "https://github.com/dilyslyu"
        title = "GitHub"
        weight = 9
    [languages.zh-cn.params]
      # 网站描述
      description = "这是 Dilys.Lyu 的个人博客。"
      # 网站关键词
      keywords = ["Dilys", "Dilys.Lyu"]
      # 应用图标配置
      [languages.zh-cn.params.app]
        # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
        title = "Dilys.Lyu"
        # 是否隐藏网站图标资源链接
        noFavicon = false
        # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
        svgFavicon = ""
        # Android 浏览器主题色
        themeColor = "#ffffff"
        # Safari 图标颜色
        iconColor = "#5bbad5"
        # Windows v8-10 磁贴颜色
        tileColor = "#da532c"
      # 搜索配置
      [languages.zh-cn.params.search]
        enable = true
        # 搜索引擎的类型 ("lunr", "algolia")
        type = "algolia"
        # 文章内容最长索引长度
        contentLength = 5000
        # 搜索框的占位提示语
        placeholder = "搜索本站"
        # 最大结果数目
        maxResultLength = 50
        # 搜索结果中高亮部分的 HTML 标签
        highlightTag = "em"
        [languages.zh-cn.params.search.algolia]
          index = "index.zh-cn"
          appID = "PASDMWALPK"
          searchKey = "b42948e51daaa93df92381c8e2ac0f93"
      # 主页信息设置
      [languages.zh-cn.params.home]
        # RSS 文章数目
        rss = 99999
        # 主页个人信息
        [languages.zh-cn.params.home.profile]
          enable = true
          # Gravatar 邮箱，用于优先在主页显示的头像
          # gravatarEmail = "jonny6015@icloud.com"
          gravatarEmail = ""
          # 主页显示头像的 URL
          avatarURL = "/images/avatar.png"
          # 主页显示的网站副标题
          subtitle = "PHP不是世界上最好的语言，JAVA才是 ..."
          # 是否为副标题显示打字机动画
          typeit = true
          # 是否显示社交账号
          social = true
          # 免责声明 (支持 HTML 格式)
          disclaimer = "<p>The content published by the <b>JonnyHub</b> does not guarantee absolute correctness, and the risks associated with using the content of this site have nothing to do with this site. If there is any infringement in this website, please contact the author and delete it.</p>"
        # 主页文章列表
        [languages.zh-cn.params.home.posts]
          enable = true
          # 主页每页显示文章数量
          paginate = 10
      # 主页的社交信息设置
      [languages.zh-cn.params.social]
        GitHub = "hellenhub"
        Zhihu = "jonny6015"
        Weibo = "jonnychang"
        Douban = "jonny6015"
        # Medium = "jonny6015"
        # Facebook = "jonny6015"
        # Twitter = "jonny6015"
        # Telegram = "hellenhub"
        Email = "jonny6015@icloud.com"
        RSS = true
        # Linkedin = "jonnychang"
        # Instagram = "jonny6015"
        Bilibili = "14371292"
        # Gitlab = ""
        # Youtubelegacy = ""
        # Youtubecustom = ""
        # Youtubechannel = ""
        # Tumblr = ""
        # Quora = ""
        # Keybase = ""
        # Pinterest = ""
        # Reddit = ""
        # Codepen = ""
        # FreeCodeCamp = ""
        # Bitbucket = ""
        # Stackoverflow = ""
        # Odnoklassniki = ""
        # VK = ""
        # Flickr = ""
        # Xing = ""
        # Snapchat = ""
        # Soundcloud = ""
        # Spotify = ""
        # Bandcamp = ""
        # Paypal = ""
        # Fivehundredpx = ""
        # Mix = ""
        # Goodreads = ""
        # Lastfm = ""
        # Foursquare = ""
        # Hackernews = ""
        # Kickstarter = ""
        # Patreon = ""
        # Steam = "xxxx"
        # Twitch = ""
        # Strava = ""
        # Skype = ""
        # Whatsapp = ""
        # Angellist = ""
        # Slidershare = ""
        # Jsfiddle = ""
        # Deviantart = ""
        # Behance = ""
        # Dribbble = ""
        # Wordpress = ""
        # Vine = ""
        # Googlescholar = ""
        # Researchgate = ""
        # Mastodon = ""
        # Thingiverse = ""
        # Devto = "xxxx"
        # Gitea = ""
        # XMPP = ""
        # Matrix = ""
