name: Auto Deploy Hugo site to Server

on:
    push:
        branches:
            - main

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-22.04
        env:
            TZ: Asia/Shanghai
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            # 1. 检出仓库
            - uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 0

            # 2. 安装 Hugo
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  hugo-version: '0.123.8'
                  extended: true

            # 3. 生成静态页面
            - name: Build
              run: hugo --minify

            # 4. 部署到服务器（可选）
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  EXCLUDE: '.well-known, .user.ini'
                  SOURCE: public/
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{ secrets.DEPLOY_DIR }}
